### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ghost** [jdesbonnet/jbdiff#2]
This only work for small file.

**Comment by jdesbonnet** [comment]
Thanks for the feedback. It has been a while since I worked on this (10 years!), but I suspect it does try to do all the processing in memory. You could try to increase the JVM heap size eg adding this option to java: -Xmx500m

**Comment by ghost** [comment]
Still same. Do you have any other project like jbdiff? Please let me know.

**Comment by jdesbonnet** [comment]
What sizes are the files you are comparing? Check out xdelta (http://xdelta.org/) or google "binary difference algorithms" for other options.  Joe.

**Comment by ghost** [comment]
thank you. Try xdelta and it works. Here i end up https://github.com/btimofeev/UniPatcher
